;#; Copyright (c) 2025 NorthernL1ghts
;#; SHA HASH: 9dc9b07597c9de2839d5816016287e7258d9d873602d9084043665d0181623aa
;#; Filename: isel-grammar.bnf
;#; Updated: 2025-05-01, 13:13:40

<match-pattern> ::= "match" <inst-spec> { <inst-spec> }
                    ( "emit" | "discard" ) ( <inst-block> | <inst-spec> )

<inst-block> ::= "{" <inst-spec> { <inst-spec> } "}"

<inst-spec> ::= <opcode> [ IDENTIFIER ] "(" { <operand> } ")"
                [ "clobbers" IDENTIFIER { [ "," ] IDENTIFIER } ";" ] [ "," ]

<operand>   ::= [ OPERAND_KIND ] IDENTIFIER [ "=" <expression> ] [ "," ]

<opcode>        ::= IDENTIFIER
<expression>    ::= IDENTIFIER | INTEGER