;#; Copyright (c) 2025 NorthernL1ghts
;#; SHA HASH: ea5317b591620541bce2935300ffc147308a6de12c7749a7da9ea3add7bfb364
;#; Filename: isel-grammar.bnf
;#; Updated: 2025-05-01, 14:06:24

<match-pattern> ::= "match" <inst-spec> { <inst-spec> }
                    ( "emit" | "discard" ) ( <inst-block> | <inst-spec> )

<inst-block> ::= "{" <inst-spec> { <inst-spec> } "}"

<inst-spec> ::= <opcode> [ IDENTIFIER ] "(" { <operand> } ")"
                [ "clobbers" IDENTIFIER { [ "," ] IDENTIFIER } ";" ] [ "," ]

<operand>   ::= [ OPERAND_KIND ] IDENTIFIER [ "=" <expression> ] [ "," ]

<opcode>        ::= IDENTIFIER
<expression>    ::= IDENTIFIER | INTEGER