;#;Copyright (c) 2025 NorthernL1ghts. All rights reserved.

;#;This file is part of the AlyCompiler.
;#;Unauthorized copying, modification, or distribution of this file,
;#;via any medium, is strictly prohibited except as permitted under
;#;the terms outlined in the LICENSE file.

;#;For licensing details, contributions, or inquiries, refer to LICENSE
;#;or contact:
;#;NorthernL1ghts

.data
gStart:
g000001: .space 32,0 ; Allocates 32 bytes of space in memory, this is pretty much a no-op in this case.
gEnd:
.code